# Production context: all deploys from the Production branch set in your site's 
# deploy contexts will inherit these settings.

[context.production]
  publish = "public/"
  command = "gatsby build"
  environment = { NODE_VERSION = "12.14.0", YARN_VERSION = "1.19.1" }
  
[build]
  base = "."
  functions = "./functions"
  command = "npm run build"
  publish = "public"